### ISSUE TITLE
Choose what data should be returned from github

### ISSUE THREAD

**Issue by marinvvasilev** [AxwayBraggers/githubModule#5]
Choose what fields should be fetched from github, and persisted to our ArrowDB.
e.g.:

* User name
* Full Name
* Reositories
  * repo stars
  * repo url
  * repo short description
  * repo languages
....

**Comment by tpopov94** [comment]
- repo open issues ?

**Comment by marinvvasilev** [comment]
@Guldjan , @zaca45 какво мислите по въпроса? Кои полета ще е удачно да съхраняваме?!

**Comment by Guldjan** [comment]
Според мен user name, repo url и repo short description.

**Comment by ghost** [comment]
username
repo (short_name, url, description )

**Comment by tpopov94** [comment]
Team participants maybe ?

**Comment by marinvvasilev** [comment]
Ако ще взимаме Team participants и т.п. полета, трябва да решим, дали ще показваме view страница на дадено repo?! @AxwayBraggers/braggers какво мислите по въпроса?

**Comment by tpopov94** [comment]
- Repo Name
- Repo Owner (Ако има някакви отборни примерно не винаги юзъра е owner)
- Repo Description
- Repo url
- Repo stars
- Repo main language

**Comment by marinvvasilev** [comment]
@tpopov94  and what about the user part. What are the fields, that we are going to persist for user's profile?!

**Comment by tpopov94** [comment]
Well, our bot is collecting from slack full name (first and last name) and email

**Comment by marinvvasilev** [comment]
And on the github side?

**Comment by tpopov94** [comment]
We can take full name (again ?), maybe location (e.g. Sofia), bio, number of followers, number of following, company. Choose some of there or all of them 
Also, we can take avatar url if we want to have images in profiles
